# Configuration file for marin-frontend-api-service
# Inform OPS team if you change this file
# Default values are dit vm values

SERVER:
  protocol: http
  host: ${service.host:-localhost}
  name: ${service.name:-marin-frontend-api-service}
  port: ${service.port:-2020}
  frontendHostname: ${service.frontendHostname}

LOCAL_DEV_TESTING: ${local-dev-testing:-false}
USE_LOCAL_CACHE: ${use-local-cache:-false}

DEFAULT_MARIN_USER_LEGACY_ID: ${default-legacy-id:-113419}

REDIS:
  enabled: ${redis.enabled:-false}
  hosts: ${redis.sentinel.url:-127.0.0.1:26379}
  name: ${redis.master.name:-redis-marin-frontend-api-service}
  defaultExpirationTimeMinutes: ${redis.default-expiration-time-minutes:-30}

TEMP_DIR: ${marin-frontend-api-service.tempDir:-/var/app_data/marin-frontend-api-service}
ENVIRONMENT: ${env:-development}
GRAPHITE_SERVER: ${graphite.host:-insert.test.host:9000}

REPORT:
  PAGE_SIZE: ${report.pagesize:-20000}
  DRIP_DROP_PAGE_SIZE: ${report.dripdroppagesize:-10000}

KAFKA:
  ZOOKEEPER_URL: ${kafka.zookeeper.hosts:-labs-kafkazk-lv-101,labs-kafkazk-lv-102,labs-kafkazk-lv-103}
  MONITOR_TIMEOUT_MINS: 10
  USER_REPORT:
    TOPIC: ${env-kafka:-devdarth}-userReportGeneration.Ready
    GROUP_ID: marin-api-user-report
  PACING_DASHBOARD_REPORT:
    TOPIC: ${env-kafka:-devdarth}-pacingDashboardReportGeneration.Ready
    GROUP_ID: marin-api-pacing-report

APM:
  NAME: ${apm.name:-dev}
  URL: ${apm.url:-http://dev-elk-apm-lv-101:8200/}

HEALTH_SERVICE_PATH: /admin/status
HEALTH_CHECK_DEPENDENCY_PARAMS:
  customerId: ${marin-frontend-api-service.healthCheckCustomerId:-12851}
  clientId: ${marin-frontend-api-service.healthCheckClientId:-1285081}
  userId: ${marin-frontend-api-service.healthCheckUserId:-125552015}
  AUDIT_LOG:
    objectId: ${marin-frontend-api-service.healthCheckAuditLogObjectId:-3367337}
    objectType: ${marin-frontend-api-service.healthCheckAuditLogObjectType:-campaigns}
  JOB_MANAGER:
    jobId: ${marin-frontend-api-service.healthCheckJobManagerJobId:-101716539}
    # TODO: Update the values when side panel service is deployed to DIT
  SIDE_PANEL:
    objectId: ${marin-frontend-api-service.healthCheckSidePanelObjectId:-3367337}
    objectType: ${marin-frontend-api-service.healthCheckSidePanelObjectType:-campaigns}
    publisherId: ${marin-frontend-api-service.healthCheckSidePanelPublisherId:-4}
    accountId: ${marin-frontend-api-service.healthCheckSidePanelAccountId:-99860}

NFS_ROOT_PATH:
  report: /var/marin/reports
  FTP: /var/marin/upload
  CMT: /var/marin/insights

SSO:
  siteID: marin
  siteSecretKey: ${marin-frontend-api-service.sso.site-secret-key:-$2a$10$azwh46JqWDBgU0erNURpiOSHVj9thP409X8llGdAGFINMd8tvXCpC}

MARIN_ONE_FEND_STORE:
  host: ${marin-one-fend-store.host}
  user: ${marin-one-fend-store.user}
  password: ${marin-one-fend-store.password}
  database: ${marin-one-fend-store.database}
  connectionLimit: ${marin-one-fend-store.connectionLimit:-2}

FEND_STORE_TABLE_NAMES:
  REPORT: report_file_meta
  SAVED_VIEWS: saved_views
  CUSTOM_COLUMNS: custom_columns
  SCHEDULED_REPORTS: scheduled_reports
  DASHBOARDS: dashboards

DATA_SERVICES:
  MARS:
    protocol: http
    host: ${mars.host:-dit-mars-lv-101.labs.marinsw.net:8899}
    pathname: /mars/v2
    healthCheck:
      serviceName: MARS
    cacheEnabled: ${mars.cacheEnabled:-false}
    cacheExpirationMinutes: ${mars.cacheExpirationMinutes:-0}

  LINKING_SERVICE:
    protocol: http
    host: ${marin-publisher-account-linking-service.host:-dit-pals-lv-101.labs.marinsw.net:8933}
    pathname: /marin-publisher-account-linking-service/public/v1.0
    healthCheck:
      serviceName: marin-publisher-account-linking-service

  LEGACY_LINKING_SERVICE:
    protocol: http
    host: ${legacy-linking-wizard.host:-searchfunc05-link-lv-101:5678 }
    pathname: /public/v1.0
    healthCheck:
      serviceName: LinkingService
      port: 8017

  CLIENTS_SERVICE:
    protocol: http
    host: ${metadata-service.host:-dit-clientmetadata-lv-101.labs.marinsw.net:9401}
    pathname: /metadata/v1.0
    healthCheck:
      serviceName: marin-metadata-service

  BULK_LAUNCHER_SERVICE:
    protocol: http
    host: ${marin-bulk-launcher-service.host:-dit-bulklauncher-lv-101.labs.marinsw.net:9601}
    pathname: /bulklauncher/v1.0
    healthCheck:
      serviceName: marin-bulk-launcher-service

  SSO_SERVICE:
    protocol: http
    host: ${marin-sso-service.host:-dit-fe-lv-103.marinsw.net}
    pathname: ''
    healthCheck:
      serviceName: marin-sso-service

  TD_SERVICE:
    protocol: http
    host: ${tds.host:-dit-tds-vip.labs.marinsw.net:8989}
    pathname: tds/data/
    healthCheck:
      serviceName: transactional-data-service
      port: 8989
      path: '/admin/marin/status/[service-name]/L1'

  JOB_MANAGER_SERVICE:
    protocol: http
    host: ${marin-job-manager-service.host:-dit-mrnjobmgr-lv-101.labs.marinsw.net:8080}
    pathname: public/v1.0/
    healthCheck:
      serviceName: marin-job-manager-service

  ACTIVITY_LOG_SERVICE:
    protocol: http
    host: ${marin-activity-log-service.host:-dit-activitylogui-lv-101.labs.marinsw.net:9701}
    pathname: als/v1.0/
    healthCheck:
      serviceName: marin-activity-log-service

  AUDIT_LOG_SERVICE:
    protocol: http
    host: ${marin-audit-log-service.host:-dit-auditlog-lv-101.labs.marinsw.net:9709}
    pathname: auditlogs/v1.0/
    healthCheck:
      serviceName: marin-audit-log-service

  URL_BUILDER_SERVICE:
    protocol: http
    host: ${marin-url-builder-service.host:-dit-pubjobcoord-lv-101.labs.marinsw.net:9877}
    pathname: ''
    healthCheck:
      serviceName: marin-url-builder-service

  URL_BUILDER_SETTINGS_SERVICE:
    protocol: http
    host: ${marin-url-builder-settings-service.host:-dit-ubs-lv-101.labs.marinsw.net:7702}
    pathname: ''
    healthCheck:
      port: 8024
      serviceName: UrlBuilderSettingsService

  SIDE_PANEL_SERVICE:
    protocol: http
    host: ${marin-publisher-object-details-service.host:-dit-kafka-lv-101.labs.marinsw.net:9717}
    pathname: marin-publisher-object-details-service/v1.0/
    healthCheck:
      serviceName: marin-publisher-object-details-service

  TRACKING_SETTINGS_SERVICE:
    protocol: http
    host: ${marin-url-builder-settings-service.host:-dit-ubs-lv-101.labs.marinsw.net:7702}
    pathname: /public/v1.0/urlBuilder/tracking
    healthCheck:
      port: 8024
      serviceName: UrlBuilderSettingsService

  CONVERSION_TYPES_SERVICE:
    protocol: http
    host: ${marin-revenue-settings-service.host:-dit-revenuesettings-lv-101.labs.marinsw.net:9715}
    pathname: marin-revenue-settings/v1.0
    healthCheck:
      serviceName: marin-revenue-settings-service

  LEGACY_SOCIAL:
    protocol: https
    host: ${marin-social-legacy-service.host:-ditapi.mysocialpixel.com}
    pathname: internal/v1.0
    healthCheck:
      serviceName:

  SOCIAL_BULK_SERVICE:
    protocol: https
    host: ${marin-social-bulk-service.host:-dit-vip-marin-social-bulk-service-lv.marinsw.net}
    pathname: ''
    healthCheck:
      serviceName: marin-social-bulk-service
      path: '/admin/status/marin-social-bulk-service'

  SOCIAL_MULTIEDIT_SERVICE:
    protocol: https
    host: ${marin-social-multiedit-service.host:-dit-vip-marin-social-multiedit-service-lv.marinsw.net}
    pathname: ''
    healthCheck:
      serviceName: marin-social-multiedit-service
      path: '/admin/status/marin-social-multiedit-service'

  SOCIAL_MESSAGE_BOOSTER_SERVICE:
    protocol: https
    host: ${marin-social-message-booster-service.host:-dit-social-messagebooster-lv-101.labs.marinsw.net}
    pathname: ''
    healthCheck:
      serviceName: marin-social-message-booster-service
      path: '/admin/status/marin-social-message-booster-service'

  CREATIVE_ASSETS_SERVICE:
    protocol: https
    host: ${marin-creative-assets-service.host:-func03-marin-cloud-asset-gateway-service-lv-101.labs.marinsw.net}
    pathname: v1
    healthCheck:
      serviceName: marin-cloud-asset-gateway-service

  CLOUD_ASSET_HOSTING_SERVICE:
    protocol: https
    host: ${marin-cloud-assets-hosting-service.host:-func03-marin-cloud-asset-hosting-service-lv-101.labs.marinsw.net}
    pathname: v1
    assetsPathname: /smapp
    healthCheck:
      serviceName: marin-cloud-asset-hosting-service

  BIDDING_SERVICE:
    protocol: http
    host: ${marin-bid-strategy-service.host:-dit-marin-bid-strategy-service-101.labs.marinsw.net:9714}
    pathname: marin-bid-strategy/v1.0/
    healthCheck:
      serviceName: marin-bid-strategy-service

  BIDDING_SERVICE_V2:
    protocol: http
    host: ${marin-hybrid-bid-strategy-service.host:-func03-marin-hybrid-bid-strategy-service-lv-101.labs.marinsw.net:9724}
    pathname: hybridbidstrategy/v1.0/
    healthCheck:
      serviceName: marin-hybrid-bid-strategy-service

  DRIP_DROP:
    protocol: http
    host: ${dripdrop.host:-localhost:8088}
    pathname: public/v1.0/
    healthCheck:
      serviceName: dripdrop
      port: 8012

  VO_SERVICE:
    protocol: http
    host: ${vo-service.host:-localhost:61623}
    pathname: public/v1.0/vos/
    healthCheck:
      serviceName: voservice
      port: 8018

  FORECAST_RETRIEVAL_SERVICE:
    protocol: http
    host: ${frs.host:-localhost:8802}
    pathname: public/v1.0/frs/
    healthCheck:
      serviceName: forecastRetrievalService
      port: 8020

  I18N_SERVICE:
    protocol: http
    host: ${marin-i18n-service.host:-dit-marin-i18n-service-lv-101.labs.marinsw.net:7788}
    pathname: marin-i18n-service/public/v1.0/
    healthCheck:
      serviceName: marin-i18n-service

  AMAZON-API-SERVICE:
    protocol: https
    host: ${marin-amazon-api-service.host:-localhost:8042}
    pathname: ''
    healthCheck:
      serviceName: marin-amazon-api-service

  INSIGHTS-SERVICE:
    protocol: http
    host: ${marin-insights-service.host}
    pathname: /v2.0/api
    healthCheck:
      serviceName: marin-insights-service
      path: '/admin/status/L1'

  RULES-SERVICE:
    protocol: https
    host: ${marin-rules-service.host:-localhost:8043}
    pathname: ''
    healthCheck:
      serviceName: marin-rules-service

TDS_CONFIG:
  report:
    schemaName: ${env:-dit}
    tableName: REPORT_FILE_META
  savedViews:
    schemaName: ${env:-dit}
    tableName: SAVED_VIEWS
  customColumns:
    schemaName: ${env:-dit}
    tableName: CUSTOM_COLUMNS
  scheduledReports:
    schemaName: ${env:-dit}
    tableName: SCHEDULED_REPORTS
  jobRules:
    schemaName: ${env:-dit}
    tableName: JOB_RULES
  jobSchedules:
    schemaName: ${env:-dit}
    tableName: JOB_SCHEDULES
  accounts:
    schemaName: ${env:-dit}
    tableName: ACCOUNTS
  dashboards:
    schemaName: ${env:-dit}
    tableName: DASHBOARDS
  users:
    schemaName: ${env:-dit}
    tableName: USERS

PERFORMANCE_LOG:
  VERSION: 1.0

SENDGRID:
  apiKey: ${sendgrid.apiKey:-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}
  fromEmail: ${sendgrid.fromEmail:-donotreply@marinsoftware.com}

CLIENT_SECRET: ${marin-frontend-api-service.client_secret:-$2a$10$azwh46JqWDBgU0erNURpiOSHVj9thP409X8llGdAGFINMd8tvXCpC}

GELF:
  host: ${gelf.host:-labs-elk-gelf-vip.labs.marinsw.net}
  port: ${gelf.port:-12201}

ACL:
  salt: ${service.acl.salt=azwh46JqWDBgU0erNURpiOSHVj9thP409X8llGdAGFINMd8tvXCpC}

TRACKER_QUICKSIGHT_DASHBOARD:
  awsAccountId: '262397785893'
  awsAccessKeyId: 'AKIAT2GBAO4S2OILV4U2'
  awsSecretAccessKey: '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'
  awsZone: 'us-east-1'
  clientIdHashKey: 'wawptw'
  itpDashboardId: ${tracker-quicksight-dashboard.itp.dashboardId:-0f843390-3445-4072-aa2b-60171c6cfa0e}
  diagnosticDashboardId: ${tracker-quicksight-dashboard.diagnostic.dashboardId:-794562ad-94ef-437d-b6aa-3a9561c159a4}
  offlineDashboardId: ${tracker-quicksight-dashboard.offline.dashboardId:-794562ad-94ef-437d-b6aa-3a9561c159a4}
  analyticsDashboardId: ${tracker-quicksight-dashboard.analytics.dashboardId:-794562ad-94ef-437d-b6aa-3a9561c159a4}
