# Configuration file for marin-frontend-api-service
# Inform OPS team if you change this file
# Default values are dit vm values

SERVER:
  protocol: http
  host: ${service.host:-localhost}
  name: ${service.name:-marin-frontend-api-service}
  port: ${service.port:-2020}
  frontendHostname: ${service.frontendHostname}

LOCAL_DEV_TESTING: ${local-dev-testing:-false}
USE_LOCAL_CACHE: ${use-local-cache:-false}

DEFAULT_MARIN_USER_LEGACY_ID: ${default-legacy-id:-113419}

APM:
  NAME: ${apm.name:-dev}
  URL: ${apm.url:-http://dev-elk-apm-lv-101:8200/}

HEALTH_SERVICE_PATH: /admin/status
HEALTH_CHECK_DEPENDENCY_PARAMS:
  customerId: ${marin-frontend-api-service.healthCheckCustomerId:-12851}
  clientId: ${marin-frontend-api-service.healthCheckClientId:-1285081}
  userId: ${marin-frontend-api-service.healthCheckUserId:-125552015}
  AUDIT_LOG:
    objectId: ${marin-frontend-api-service.healthCheckAuditLogObjectId:-3367337}
    objectType: ${marin-frontend-api-service.healthCheckAuditLogObjectType:-campaigns}
  JOB_MANAGER:
    jobId: ${marin-frontend-api-service.healthCheckJobManagerJobId:-101716539}
    # TODO: Update the values when side panel service is deployed to DIT
  SIDE_PANEL:
    objectId: ${marin-frontend-api-service.healthCheckSidePanelObjectId:-3367337}
    objectType: ${marin-frontend-api-service.healthCheckSidePanelObjectType:-campaigns}
    publisherId: ${marin-frontend-api-service.healthCheckSidePanelPublisherId:-4}
    accountId: ${marin-frontend-api-service.healthCheckSidePanelAccountId:-99860}


SENDGRID:
  apiUser: ${sendgrid.apiUser:-sendGridApiUser}
  apiKey: ${sendgrid.apiKey:-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}
  fromEmail: ${sendgrid.fromEmail:-donotreply@marinsoftware.com}

LIMIT_BREACHED_EMAIL_TO: ${limit-breached-email-to:-donotreply@marinsoftware.com}

API_URL: ${API_URL:-https://developer.api.stg.walmart.com/api-proxy/service/WPA/Api/v1/api/v1/}
CONSUMER_ID: ${CONSUMER_ID:-marin-decodermind}
AUTH_TOKEN: ${AUTH_TOKEN:-marin-decodermind}
VERSION: ${VERSION:-1}
APP_ID: ${APP_ID:-marin-decodermind}
SECRET_ADS: ${SECRET_ADS:-marin-decodermind}
REDIRECT_URI: ${REDIRECT_URI:-https://marin-decodermind.net/transientPage}
REDIRECT_URI_JUSTADS: ${REDIRECT_URI_JUSTADS:-https://marin-decodermind.net:3001/decodeOAuthUrl}
REDIRECT_V1_URI_JUSTADS: ${REDIRECT_V1_URI_JUSTADS:-https://marin-decodermind.com:3001/api/v1/decodeOAuthUrl}