# Configuration file for marin-frontend-api-service
# Inform OPS team if you change this file
# Default values are dit vm values

SERVER:
  protocol: http
  host: ${service.host:-localhost}
  name: ${service.name:-marin-frontend-api-service}
  port: ${service.port:-2020}
  frontendHostname: ${service.frontendHostname}

GELF:
  host: ${gelf.host:-labs-elk-gelf-vip.labs.marinsw.net}
  port: ${gelf.port:-12201}

