# Configuration file for marin-frontend-api-service
# Inform OPS team if you change this file
# Default values are dit vm values

SERVER:
  protocol: http
  host: ${service.host:-localhost}
  name: ${service.name:-marin-frontend-api-service}
  port: ${service.port:-2020}
  frontendHostname: ${service.frontendHostname}

LOCAL_DEV_TESTING: ${local-dev-testing:-false}
USE_LOCAL_CACHE: ${use-local-cache:-false}

DEFAULT_MARIN_USER_LEGACY_ID: ${default-legacy-id:-113419}

REDIS:
  enabled: ${redis.enabled:-false}
  hosts: ${redis.sentinel.url:-127.0.0.1:26379}
  name: ${redis.master.name:-redis-marin-frontend-api-service}
  defaultExpirationTimeMinutes: ${redis.default-expiration-time-minutes:-30}

TEMP_DIR: ${marin-frontend-api-service.tempDir:-/var/app_data/marin-frontend-api-service}
ENVIRONMENT: ${env:-development}
GRAPHITE_SERVER: ${graphite.host:-insert.test.host:9000}

REPORT:
  PAGE_SIZE: ${report.pagesize:-20000}
  DRIP_DROP_PAGE_SIZE: ${report.dripdroppagesize:-10000}

KAFKA:
  ZOOKEEPER_URL: ${kafka.zookeeper.hosts:-labs-kafkazk-lv-101,labs-kafkazk-lv-102,labs-kafkazk-lv-103}
  MONITOR_TIMEOUT_MINS: 10
  USER_REPORT:
    TOPIC: ${env-kafka:-devdarth}-userReportGeneration.Ready
    GROUP_ID: marin-api-user-report
  PACING_DASHBOARD_REPORT:
    TOPIC: ${env-kafka:-devdarth}-pacingDashboardReportGeneration.Ready
    GROUP_ID: marin-api-pacing-report

APM:
  NAME: ${apm.name:-dev}
  URL: ${apm.url:-http://dev-elk-apm-lv-101:8200/}

HEALTH_SERVICE_PATH: /admin/status
HEALTH_CHECK_DEPENDENCY_PARAMS:
  customerId: ${marin-frontend-api-service.healthCheckCustomerId:-12851}
  clientId: ${marin-frontend-api-service.healthCheckClientId:-1285081}
  userId: ${marin-frontend-api-service.healthCheckUserId:-125552015}
  AUDIT_LOG:
    objectId: ${marin-frontend-api-service.healthCheckAuditLogObjectId:-3367337}
    objectType: ${marin-frontend-api-service.healthCheckAuditLogObjectType:-campaigns}
  JOB_MANAGER:
    jobId: ${marin-frontend-api-service.healthCheckJobManagerJobId:-101716539}
    # TODO: Update the values when side panel service is deployed to DIT
  SIDE_PANEL:
    objectId: ${marin-frontend-api-service.healthCheckSidePanelObjectId:-3367337}
    objectType: ${marin-frontend-api-service.healthCheckSidePanelObjectType:-campaigns}
    publisherId: ${marin-frontend-api-service.healthCheckSidePanelPublisherId:-4}
    accountId: ${marin-frontend-api-service.healthCheckSidePanelAccountId:-99860}

NFS_ROOT_PATH:
  report: /var/marin/reports
  FTP: /var/marin/upload
  CMT: /var/marin/insights

SSO:
  siteID: marin
  siteSecretKey: ${marin-frontend-api-service.sso.site-secret-key:-$2a$10$azwh46JqWDBgU0erNURpiOSHVj9thP409X8llGdAGFINMd8tvXCpC}


  SSO_SERVICE:
    protocol: http
    host: ${marin-sso-service.host:-dit-fe-lv-103.marinsw.net}
    pathname: ''
    healthCheck:
      serviceName: marin-sso-service


SENDGRID:
  apiKey: ${sendgrid.apiKey:-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}
  fromEmail: ${sendgrid.fromEmail:-donotreply@marinsoftware.com}

CLIENT_SECRET: ${marin-frontend-api-service.client_secret:-$2a$10$azwh46JqWDBgU0erNURpiOSHVj9thP409X8llGdAGFINMd8tvXCpC}

GELF:
  host: ${gelf.host:-labs-elk-gelf-vip.labs.marinsw.net}
  port: ${gelf.port:-12201}



TRACKER_QUICKSIGHT_DASHBOARD:
  awsAccountId: '262397785893'
  awsAccessKeyId: 'AKIAT2GBAO4S2OILV4U2'
  awsSecretAccessKey: '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'
  awsZone: 'us-east-1'
  clientIdHashKey: 'wawptw'
  itpDashboardId: ${tracker-quicksight-dashboard.itp.dashboardId:-0f843390-3445-4072-aa2b-60171c6cfa0e}
  diagnosticDashboardId: ${tracker-quicksight-dashboard.diagnostic.dashboardId:-794562ad-94ef-437d-b6aa-3a9561c159a4}
  offlineDashboardId: ${tracker-quicksight-dashboard.offline.dashboardId:-794562ad-94ef-437d-b6aa-3a9561c159a4}
  analyticsDashboardId: ${tracker-quicksight-dashboard.analytics.dashboardId:-794562ad-94ef-437d-b6aa-3a9561c159a4}
